const fs=require('fs'),path=require('path');
const {chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'frontend-results.json'),release=JSON.parse(fs.readFileSync(path.join(root,'Draupr/src/config/release.json'),'utf8'));const checks=[];const add=(name,pass,detail='')=>checks.push({name,pass:!!pass,...(detail?{detail}: {})});let browser,info;
try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/local/bin/chromium',args:['--no-sandbox','--allow-file-access-from-files']});const page=await browser.newPage({viewport:{width:610,height:820}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.join(root,'Draupr/src/ui/panel.html'));await page.waitForTimeout(2400);
info=await page.evaluate(()=>({version:document.getElementById('version').textContent,tools:window.DRAUPR_SCHEMA.tools.map(t=>({id:t.id,category:t.category,fields:t.fields.length})),fieldCount:window.DRAUPR_SCHEMA.tools.reduce((n,t)=>n+t.fields.length,0),workspaces:[...document.querySelectorAll('#workspaces button')].map(b=>b.dataset.workspace),unitOptions:[...document.querySelectorAll('#units option')].map(o=>o.value),testHook:!!window.Draupr?.__test}));
add('Release badge',info.version===`${release.version} · ${release.status}`,info.version);add(`${release.tool_count} schema tools`,info.tools.length===release.tool_count,String(info.tools.length));add(`${release.field_count} schema fields`,info.fieldCount===release.field_count,String(info.fieldCount));add('Frontend test hook',info.testHook);add('Six workspaces',JSON.stringify(info.workspaces)===JSON.stringify(['create','edit','modify','materials','library','project']),info.workspaces.join(','));add('Display unit choices',JSON.stringify(info.unitOptions)===JSON.stringify(['mm','cm','m','in','ft','model']),info.unitOptions.join(','));
for(const w of info.workspaces){await page.click(`#workspaces button[data-workspace="${w}"]`);add(`Workspace ${w} renders`,await page.locator(`#view-${w}`).evaluate(e=>!e.hidden));}
await page.click('#workspaces button[data-workspace="modify"]');const modifierGroups=await page.locator('#view-modify .modifier-group').count();add('Seven Modify accordion groups',modifierGroups===7,String(modifierGroups));const modifierButtons=['modifySplit','modifyTrim','modifyAlignBaseline','modifyJunction','attachTop','attachBase','detachBoundary','modifyStep','modifyHealOpening','modifySplayOpening','modifySweep','modifyDisassemble','modifyEdgeDetail'];for(const id of modifierButtons)add(`Modifier ${id} renders`,await page.locator('#'+id).count()===1);
await page.click('#workspaces button[data-workspace="create"]');
for(const t of info.tools){await page.selectOption('#category',t.category);await page.click(`#tools button[data-tool="${t.id}"]`);const n=await page.locator('#createFields [data-field]').count();add(`${t.id}: all fields render`,n===t.fields,`${n}/${t.fields}`);}
await page.selectOption('#category','architecture');await page.click('#tools button[data-tool="molding"]');const pathSources=await page.locator('#pathSource option').evaluateAll(options=>options.map(o=>o.value));add('Linear tools expose three path input modes',JSON.stringify(pathSources)===JSON.stringify(['draw','selected','pick']),pathSources.join(','));await page.selectOption('#pathSource','selected');await page.dispatchEvent('#pathSource','change');add('Selected-edge mode exposes Generate action',await page.locator('#draw').textContent().then(v=>v.includes('Generate')));
for(const width of [420,610,900]){await page.setViewportSize({width,height:820});const ok=await page.locator('#workspaces').evaluate(e=>e.scrollWidth<=e.clientWidth+1);add(`Workspace navigation fits ${width}px`,ok,`${await page.locator('#workspaces').evaluate(e=>e.scrollWidth)}/${width}`);}
await page.selectOption('#category','architecture');await page.click('#tools button[data-tool="dormer"]');const dormerThumbCount=await page.locator('.dormer-type-grid button').count();add('Dormer gallery renders nine thumbnails',dormerThumbCount===9,String(dormerThumbCount));
await page.selectOption('#language','fa');add('Persian RTL layout',await page.locator('html').getAttribute('dir')==='rtl');add('No frontend runtime errors',errors.length===0,errors.join(' | '));
}catch(e){add('Runner completed',false,e.stack||e.message)}finally{if(browser)await browser.close();}
const result={release:`${release.version} ${release.status}`,kind:'Headless Chromium frontend rendering checks; not SketchUp native runtime tests',schema_tool_count:info?.tools?.length||release.tool_count,schema_field_count:info?.fieldCount||release.field_count,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed}));if(result.failed)process.exit(1);
})();
